# Generated by Django 3.2.9 on 2021-11-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20211119_1418'),
        ('reserve', '0003_alter_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.address'),
            preserve_default=False,
        ),
    ]
