# Generated by Django 3.2.9 on 2021-11-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_staff_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='author',
            new_name='address',
        ),
    ]
