# Generated by Django 3.2.9 on 2021-11-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='address',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='プロフィール画像'),
        ),
    ]
