# Generated by Django 3.2.9 on 2021-11-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal',
            field=models.CharField(default=1, max_length=30, verbose_name='名前'),
            preserve_default=False,
        ),
    ]
